os:
    - linux

language: cpp

sudo: required
dist: trusty

install:
  - cd ~
  - sudo apt-add-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc-5 g++-5 xorg-dev libglu1-mesa-dev libsdl2-dev libx11-dev libxcursor-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

script:
  - cd "$TRAVIS_BUILD_DIR"
  - mkdir cbuild && cd cbuild
  - cmake ..
  - make -j4
